include:
- notification_management_pkg/*
kind: ArchiveUploadSpec
name: notification-management-pkg-FrAJ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: notification-management-co-928c21ed-ea58-497b-ab27-40d2dd0ee4ac
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://notification-management-pkg-FrAJ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-06T05:44:00Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: notification-management-consumer
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: notification_management.main.message_queue_entrypoint
    packageref:
      name: notification-management-co-928c21ed-ea58-497b-ab27-40d2dd0ee4ac
      namespace: ""
  requestsPerPod: 1
  resources: {}
